const fabToggle = document.getElementById("fabToggle");
const fabContainer = document.querySelector(".fab-container");

if (fabToggle && fabContainer) {
    fabToggle.addEventListener("click", () => {
        fabContainer.classList.toggle("open");
    });
}

window.translations = window.translations || {};

window.translations.floraFauna = {
    es: {
        nav_inicio: "Inicio",
        nav_senderos: "Senderos",
        nav_comunidad: "Comunidad",
        nav_flora: "Flora y Fauna",
        nav_emprendedores: "Emprendedores",
        nav_videos: "Videos",
        nav_bandera: "Bandera Azul Ecológica",

        hero_tag: "Sitio RAMSAR • Biodiversidad extraordinaria",
        hero_title: "Flora y Fauna de <span>Caño Negro</span>",
        hero_desc: "Caño Negro es uno de los humedales más importantes del mundo, donde la vegetación, el agua y la vida silvestre forman un paisaje dinámico y de enorme valor ecológico para Costa Rica.",

        nav_internal_overview: "Visión general",
        nav_internal_flora: "Flora",
        nav_internal_fauna: "Fauna",
        nav_internal_birds: "Aves",
        nav_internal_mammals: "Mamíferos",
        nav_internal_fish: "Peces",
        nav_internal_reptiles: "Reptiles",
        nav_internal_amphibians: "Anfibios",

        overview_label: "Panorama ecológico",
        overview_title: "Un humedal donde todo está conectado",
        overview_subtitle: "En Caño Negro, la flora y la fauna no se entienden por separado. Los cambios en el nivel del agua modifican el paisaje, influyen en la vegetación y determinan la presencia de aves migratorias, reptiles, mamíferos, peces y anfibios.",
        overview_card1_title: "Flora adaptada al agua",
        overview_card1_desc: "La vegetación del humedal soporta inundaciones, sequías temporales y cambios estacionales que transforman por completo el ecosistema.",
        overview_card2_title: "Fauna de gran valor",
        overview_card2_desc: "Caño Negro es un punto clave para especies residentes y migratorias, especialmente aves, además de reptiles, peces, mamíferos y anfibios.",
        overview_card3_title: "Dinámica estacional",
        overview_card3_desc: "En época lluviosa predominan aguas extensas y vegetación flotante; en época seca emergen playones y pastos que cambian la oferta de alimento.",
        overview_card4_title: "Importancia de conservación",
        overview_card4_desc: "Más que la cantidad de especies, destaca su papel como refugio para plantas y animales que han disminuido en otras zonas de Centroamérica.",

        flora_label: "Flora",
        flora_title: "Vegetación que define el paisaje del humedal",
        flora_subtitle: "Caño Negro alberga más de 300 especies de plantas registradas, entre árboles, herbáceas, palmas y vegetación acuática. Su flora representa aproximadamente el 3% de la flora nativa de Costa Rica y es un ejemplo notable de adaptación a ambientes inundables.",
        flora_stat1: "especies registradas",
        flora_stat2: "tipos de árboles",
        flora_stat3: "especies herbáceas",
        flora_stat4: "especies de palmas",

        flora_feature1_label: "Ecosistema emblemático",
        flora_feature1_title: "El Yolillal",
        flora_feature1_desc1: "El <strong>Yolillo (Raphia taedigera)</strong> domina uno de los ecosistemas más característicos de Caño Negro. Estas palmas viven con sus raíces sumergidas y forman agrupaciones densas que sirven de refugio a numerosas especies animales.",
        flora_feature1_desc2: "Más que una especie aislada, el yolillal representa una estructura vegetal que da identidad al paisaje y define buena parte de la dinámica ecológica del humedal.",

        flora_feature2_label: "Bosques adaptados al encharcamiento",
        flora_feature2_title: "Marillal y bosque inundado",
        flora_feature2_desc1: "En estas zonas sobresalen especies como la <strong>María (Calophyllum brasiliense)</strong>, el <strong>Camíbar (Copaifera aromatica)</strong> y el <strong>Palo de Agua o Poponjoche (Pachira aquatica)</strong>.",
        flora_feature2_desc2: "Son bosques que permanecen bajo el agua gran parte del año. Sus especies están adaptadas a suelos saturados y cumplen un papel fundamental en la estructura vegetal del humedal.",

        flora_panel1_title: "Vegetación herbácea y acuática",
        flora_panel1_desc: "En lagunas y caños aparecen “alfombras” flotantes de plantas que cumplen un papel vital en la oxigenación y el equilibrio del agua.",
        flora_panel1_item1: "Lirio de agua <em>(Eichhornia crassipes)</em>",
        flora_panel1_item2: "Pasto Gamalote <em>(Paspalum fasciculatum)</em>",
        flora_panel1_item3: "Dormilona <em>(Mimosa pigra)</em>",
        flora_panel1_item4: "Lechuga de agua <em>(Pistia stratiotes)</em>",
        flora_panel1_item5: "Helechos acuáticos <em>(Salvinia)</em>",

        flora_panel2_title: "Palma Cuba",
        flora_panel2_desc: "Es una de las plantas más especiales de Caño Negro. En Costa Rica, su distribución natural está casi limitada a los humedales de la Zona Norte. Crece en colonias densas y aporta una imagen única al paisaje.",

        flora_panel3_title: "Adaptación estacional",
        flora_panel3_desc: "En época lluviosa predomina la vegetación flotante y emergente. En época seca, el nivel del agua baja drásticamente, aparecen playones y surgen pastos que alimentan a numerosas aves migratorias.",

        flora_panel4_title: "Refugio de biodiversidad regional",
        flora_panel4_desc: "Caño Negro funciona como refugio para plantas de distribución restringida o poco comunes en otras regiones, lo que aumenta su importancia para la conservación.",

        flora_sub_label: "Valor botánico",
        flora_sub_title: "Aspectos que hacen única a la flora de Caño Negro",
        flora_sub_subtitle: "Además de su riqueza de especies, el humedal destaca por sus asociaciones vegetales, su conectividad ecológica y la presencia de plantas con distribución restringida en Costa Rica.",

        flora_unique1_title: "Asociaciones vegetales",
        flora_unique1_desc: "La flora de Caño Negro se organiza en distintas asociaciones según el nivel de inundación. Este patrón determina qué especies logran desarrollarse y da forma al paisaje del humedal.",
        flora_unique1_item1: "<strong>Yolillal:</strong> dominado por palma yolillo en áreas permanentemente inundadas",
        flora_unique1_item2: "<strong>Marillal y bosque inundado:</strong> árboles adaptados a suelos saturados",
        flora_unique1_item3: "<strong>Vegetación herbácea:</strong> plantas flotantes o emergentes en lagunas y caños",

        flora_unique2_title: "Especies de distribución restringida",
        flora_unique2_desc: "Algunas plantas presentes en Caño Negro tienen una distribución natural muy limitada en Costa Rica, lo que refuerza su valor ecológico y científico.",
        flora_unique2_item1: "<strong>Palma Cuba (Acoelorraphe wrightii):</strong> casi limitada a humedales del norte",
        flora_unique2_item2: "<strong>Yolillo:</strong> forma uno de los ecosistemas más extensos y conservados de la región",
        flora_unique2_item3: "<strong>Orquídeas y epífitas de humedal:</strong> especies raras asociadas a ambientes inundados",

        flora_unique3_title: "Conectividad ecológica",
        flora_unique3_desc1: "Debido a la conexión del Río Frío con el Lago de Nicaragua, gran parte de la flora de Caño Negro se comparte entre ambos países, formando un corredor biológico binacional.",
        flora_unique3_desc2: "Esta conectividad favorece el intercambio natural de especies y fortalece la biodiversidad regional.",

        flora_unique4_title: "El reto de la conservación",
        flora_unique4_desc1: "Más que por la cantidad de especies estrictamente endémicas, Caño Negro destaca por actuar como un “arca de Noé” para plantas que han desaparecido en otras zonas de Centroamérica debido a la agricultura y la ganadería.",
        flora_unique4_desc2: "También conserva poblaciones valiosas de especies raras o históricamente presionadas, como la caoba <em>(Swietenia macrophylla)</em>.",

        fauna_label: "Fauna",
        fauna_title: "Una diversidad que cambia con el agua y las estaciones",
        fauna_subtitle: "La fauna de Caño Negro responde directamente a la dinámica del humedal. En algunos momentos predominan los espejos de agua y las aves acuáticas; en otros, los playones y zonas abiertas favorecen nuevos movimientos de especies.",
        fauna_box1_title: "Aves",
        fauna_box1_desc: "Incluye aves migratorias y residentes; es el grupo más abundante y uno de los mayores atractivos del refugio.",
        fauna_box2_title: "Mamíferos",
        fauna_box2_desc: "Destacan 90 especies de murciélagos y 70 especies terrestres, incluyendo felinos, primates y otras especies asociadas a bosques y humedales.",
        fauna_box3_title: "Peces",
        fauna_box3_desc: "Claves para el equilibrio acuático del humedal. Sobresale el gaspar, una especie simbólica y de gran valor biológico.",
        fauna_box4_title: "Reptiles",
        fauna_box4_desc: "Destacan caimanes, cocodrilos, tortugas y otros reptiles ligados a lagunas, orillas, canales y zonas inundables.",
        fauna_box5_title: "Anfibios",
        fauna_box5_desc: "Indicadores ecológicos del estado ambiental del ecosistema.",

        birds_tag: "Fauna destacada",
        birds_title: "Aves",
        birds_desc1: "Caño Negro es un santuario para la observación de aves. Este grupo constituye el mayor atractivo del refugio debido a la presencia de especies residentes y migratorias que utilizan el humedal como sitio de alimentación, descanso y reproducción.",
        birds_desc2: "<strong>Residentes:</strong> Aproximadamente 206 especies habitan el refugio durante todo el año.<br><strong>Migratorias:</strong> Alrededor de 101 especies visitan el humedal durante el invierno del hemisferio norte.",
        birds_desc3: "<strong>Especies clave:</strong> destacan la Garza Agamí (<em>Agamia agami</em>), el Jabirú (en peligro de extinción), la Espátula Rosada, el Cigüeñón y el Pájaro Serpiente o pato aguja (<em>Anhinga</em>).",
        birds_desc4: "La riqueza avifaunística convierte a Caño Negro en uno de los espacios más importantes para el avistamiento en Costa Rica.",
        birds_side_title: "Datos clave",
        birds_side_1: "315 a 400 especies aproximadas",
        birds_side_2: "Grupo más numeroso del humedal",
        birds_side_3: "Presencia de residentes y migratorias",
        birds_side_4: "Gran valor para observación y fotografía",

        mammals_tag: "Fauna terrestre",
        mammals_title: "Mamíferos",
        mammals_desc1: "Caño Negro alberga una gran variedad de mamíferos. Entre ellos sobresalen especies de murciélagos, felinos, monos y otros animales que encuentran refugio en los bosques, zonas inundables y áreas ribereñas del humedal.",
        mammals_desc2: "Esta diversidad refleja la complejidad ecológica del refugio, ya que la presencia de mamíferos depende de la cobertura vegetal, la disponibilidad de agua y la conexión entre distintos ambientes naturales.",
        mammals_desc3: "Entre los mamíferos más representativos se han registrado el <strong>Jaguar</strong>, la <strong>Danta o Tapir</strong>, el <strong>Puma</strong> y el <strong>Manatí</strong>, este último muy raro y en peligro. También es común observar primates como el <strong>Mono Congo</strong>, el <strong>Mono Carablanca</strong> y el <strong>Mono Colorado o Mono Araña</strong>.",
        mammals_side_title: "Especies representativas",
        mammals_side_1: "Mono carablanca",
        mammals_side_2: "Mono congo",
        mammals_side_3: "Puma",
        mammals_side_4: "Danta o tapir",

        fish_tag: "Vida acuática",
        fish_title: "Peces",
        fish_desc1: "El sistema hídrico del Río Frío alberga especies de gran valor científico y comercial, siendo el <strong>Gaspar (Atractosteus tropicus)</strong> uno de los más representativos. Este pez es considerado un “fósil viviente” por su apariencia prehistórica, y Caño Negro es uno de los pocos lugares donde se protege.",
        fish_desc2: "Además del gaspar, habitan otras especies importantes como el <strong>Sábalo real</strong>, <strong>Guapote</strong>, <strong>Róbalo</strong> y diversas <strong>Mojarras</strong>, todas fundamentales para el equilibrio del ecosistema acuático.",
        fish_desc3: "Su presencia mantiene la cadena alimenticia y está estrechamente relacionada con la dinámica del agua, la vegetación acuática y la reproducción de otras especies asociadas a lagunas, caños y zonas inundables.",
        fish_side_title: "Dato destacado",
        fish_side_1: "49 a 55 especies aproximadas",
        fish_side_2: "Incluye al Gaspar",
        fish_side_3: "Relación directa con lagunas y caños",
        fish_side_4: "Clave en el equilibrio ecológico acuático",

        reptiles_tag: "Ambientes ribereños",
        reptiles_title: "Reptiles",
        reptiles_desc1: "Los reptiles de Caño Negro están estrechamente ligados a canales, lagunas, riberas y sectores de vegetación densa. Caimanes, tortugas, basiliscos e iguanas forman parte de la identidad visual y ecológica del humedal.",
        reptiles_desc2: "Su abundancia muestra la capacidad del refugio para sostener especies adaptadas a ecosistemas acuáticos y semiacuáticos, donde el calor, el agua y la cobertura vegetal crean condiciones ideales para su supervivencia.",
        reptiles_desc3: "Caño Negro es famoso por presentar una de las mayores concentraciones de <strong>Caimán de Anteojos</strong> y <strong>Cocodrilos</strong> en la zona norte, además de especies como la <strong>Tortuga Jicotea</strong>, muy asociadas a los cuerpos de agua del humedal.",
        reptiles_side_title: "Observación común",
        reptiles_side_1: "Caimán de anteojos",
        reptiles_side_2: "Tortuga jicotea",
        reptiles_side_3: "Basilisco",
        reptiles_side_4: "Iguana verde",

        amphibians_tag: "Indicadores ambientales",
        amphibians_title: "Anfibios",
        amphibians_desc1: "Los anfibios dependen de ambientes húmedos y saludables, por lo que su presencia es una señal importante del estado ecológico de Caño Negro. Ranas y sapos participan activamente en el equilibrio del ecosistema y en el control natural de insectos.",
        amphibians_desc2: "Aunque son menos visibles que otros grupos, su valor ecológico es enorme, ya que reaccionan con rapidez a los cambios ambientales y ayudan a comprender la salud del humedal.",
        amphibians_side_title: "Importancia ecológica",
        amphibians_side_1: "Más de 30 especies",
        amphibians_side_2: "Dependencia de humedad constante",
        amphibians_side_3: "Control natural de insectos",
        amphibians_side_4: "Indicadores del estado ambiental",

        extra_label: "Diversidad biológica",
        extra_title: "Variedad, estacionalidad y vida silvestre",
        extra_subtitle: "La biodiversidad de Caño Negro también se entiende a partir de los cambios estacionales, que modifican la distribución de la fauna y favorecen la observación de especies poco comunes en otras regiones del país.",
        extra_card1_title: "Nota sobre variedades",
        extra_card1_desc: "Cuando se habla de “variedades” en términos biológicos, se hace referencia a la diversidad genética dentro de las especies. En Caño Negro, esta riqueza se ve impulsada por la dinámica natural del humedal.",
        extra_card2_title: "Época seca",
        extra_card2_desc: "Durante la estación seca, entre enero y abril, el agua se reduce a pequeñas lagunas, concentrando la fauna y facilitando el avistamiento de especies específicas de aves acuáticas.",
        extra_card3_title: "Avistamiento especial",
        extra_card3_desc: "Esta dinámica permite observar especies y comportamientos que no siempre se presentan en otras partes de Costa Rica, lo que aumenta el valor ecológico y turístico del refugio.",
        extra_card4_title: "Dato curioso",
        extra_card4_desc: "Caño Negro es considerado uno de los humedales más importantes del mundo por la extraordinaria densidad de vida silvestre que puede sostener por hectárea.",

        closing_tag: "CAÑO NEGRO",
        closing_title: "La riqueza del humedal está en la relación entre su flora, su fauna y el agua",
        closing_desc: "Comprender Caño Negro es entender cómo cada planta, cada espejo de agua y cada especie forman parte de un sistema vivo. Su conservación protege uno de los paisajes ecológicos más valiosos de Costa Rica.",

        btn_more_info: "Ver más información",
        footer_text: "© 2026 ADI Caño Negro - Todos los derechos reservados"
    },

    en: {
        nav_inicio: "Home",
        nav_senderos: "Trails",
        nav_comunidad: "Community",
        nav_flora: "Flora & Fauna",
        nav_emprendedores: "Entrepreneurs",
        nav_videos: "Videos",
        nav_bandera: "Blue Ecological Flag",

        hero_tag: "RAMSAR Site • Extraordinary biodiversity",
        hero_title: "Flora and Fauna of <span>Caño Negro</span>",
        hero_desc: "Caño Negro is one of the most important wetlands in the world, where vegetation, water, and wildlife create a dynamic landscape of enormous ecological value for Costa Rica.",

        nav_internal_overview: "Overview",
        nav_internal_flora: "Flora",
        nav_internal_fauna: "Fauna",
        nav_internal_birds: "Birds",
        nav_internal_mammals: "Mammals",
        nav_internal_fish: "Fish",
        nav_internal_reptiles: "Reptiles",
        nav_internal_amphibians: "Amphibians",

        overview_label: "Ecological overview",
        overview_title: "A wetland where everything is connected",
        overview_subtitle: "In Caño Negro, flora and fauna cannot be understood separately. Changes in water level modify the landscape, influence vegetation, and determine the presence of migratory birds, reptiles, mammals, fish, and amphibians.",
        overview_card1_title: "Water-adapted flora",
        overview_card1_desc: "Wetland vegetation withstands floods, temporary droughts, and seasonal changes that completely transform the ecosystem.",
        overview_card2_title: "High-value fauna",
        overview_card2_desc: "Caño Negro is a key site for resident and migratory species, especially birds, as well as reptiles, fish, mammals, and amphibians.",
        overview_card3_title: "Seasonal dynamics",
        overview_card3_desc: "During the rainy season, large water surfaces and floating vegetation dominate; in the dry season, mudflats and grasses emerge, changing food availability.",
        overview_card4_title: "Conservation importance",
        overview_card4_desc: "More than the number of species, its role as a refuge for plants and animals that have declined in other parts of Central America stands out.",

        flora_label: "Flora",
        flora_title: "Vegetation that shapes the wetland landscape",
        flora_subtitle: "Caño Negro hosts more than 300 recorded plant species, including trees, herbs, palms, and aquatic vegetation. Its flora represents approximately 3% of Costa Rica’s native flora and is a remarkable example of adaptation to flood-prone environments.",
        flora_stat1: "recorded species",
        flora_stat2: "tree types",
        flora_stat3: "herbaceous species",
        flora_stat4: "palm species",

        flora_feature1_label: "Iconic ecosystem",
        flora_feature1_title: "The Yolillal",
        flora_feature1_desc1: "The <strong>Yolillo palm (Raphia taedigera)</strong> dominates one of the most characteristic ecosystems of Caño Negro. These palms live with their roots submerged and form dense stands that shelter numerous animal species.",
        flora_feature1_desc2: "More than an isolated species, the yolillal represents a plant structure that gives identity to the landscape and defines much of the wetland’s ecological dynamics.",

        flora_feature2_label: "Forests adapted to waterlogging",
        flora_feature2_title: "Marillal and flooded forest",
        flora_feature2_desc1: "In these areas, species such as <strong>María (Calophyllum brasiliense)</strong>, <strong>Camíbar (Copaifera aromatica)</strong>, and <strong>Water Tree or Poponjoche (Pachira aquatica)</strong> stand out.",
        flora_feature2_desc2: "These forests remain underwater for much of the year. Their species are adapted to saturated soils and play a fundamental role in the wetland’s plant structure.",

        flora_panel1_title: "Herbaceous and aquatic vegetation",
        flora_panel1_desc: "In lagoons and channels, floating “carpets” of plants appear, playing a vital role in oxygenation and water balance.",
        flora_panel1_item1: "Water hyacinth <em>(Eichhornia crassipes)</em>",
        flora_panel1_item2: "Gamalote grass <em>(Paspalum fasciculatum)</em>",
        flora_panel1_item3: "Sensitive plant <em>(Mimosa pigra)</em>",
        flora_panel1_item4: "Water lettuce <em>(Pistia stratiotes)</em>",
        flora_panel1_item5: "Aquatic ferns <em>(Salvinia)</em>",

        flora_panel2_title: "Cuba Palm",
        flora_panel2_desc: "It is one of the most special plants in Caño Negro. In Costa Rica, its natural distribution is almost limited to the wetlands of the Northern Zone. It grows in dense colonies and gives the landscape a unique appearance.",

        flora_panel3_title: "Seasonal adaptation",
        flora_panel3_desc: "During the rainy season, floating and emergent vegetation predominates. In the dry season, water levels drop drastically, mudflats appear, and grasses emerge that feed numerous migratory birds.",

        flora_panel4_title: "Regional biodiversity refuge",
        flora_panel4_desc: "Caño Negro serves as a refuge for plants with restricted distribution or uncommon presence in other regions, increasing its importance for conservation.",

        flora_sub_label: "Botanical value",
        flora_sub_title: "What makes the flora of Caño Negro unique",
        flora_sub_subtitle: "In addition to its species richness, the wetland stands out for its plant associations, ecological connectivity, and the presence of plants with restricted distribution in Costa Rica.",

        flora_unique1_title: "Plant associations",
        flora_unique1_desc: "The flora of Caño Negro is organized into different associations depending on the level of flooding. This pattern determines which species can develop and shapes the wetland landscape.",
        flora_unique1_item1: "<strong>Yolillal:</strong> dominated by yolillo palm in permanently flooded areas",
        flora_unique1_item2: "<strong>Marillal and flooded forest:</strong> trees adapted to saturated soils",
        flora_unique1_item3: "<strong>Herbaceous vegetation:</strong> floating or emergent plants in lagoons and channels",

        flora_unique2_title: "Restricted-distribution species",
        flora_unique2_desc: "Some plants present in Caño Negro have a very limited natural distribution in Costa Rica, reinforcing their ecological and scientific value.",
        flora_unique2_item1: "<strong>Cuba Palm (Acoelorraphe wrightii):</strong> almost limited to northern wetlands",
        flora_unique2_item2: "<strong>Yolillo:</strong> forms one of the most extensive and best-preserved ecosystems in the region",
        flora_unique2_item3: "<strong>Wetland orchids and epiphytes:</strong> rare species associated with flooded environments",

        flora_unique3_title: "Ecological connectivity",
        flora_unique3_desc1: "Due to the connection between the Frío River and Lake Nicaragua, much of the flora of Caño Negro is shared between both countries, forming a binational biological corridor.",
        flora_unique3_desc2: "This connectivity encourages the natural exchange of species and strengthens regional biodiversity.",

        flora_unique4_title: "The conservation challenge",
        flora_unique4_desc1: "More than for the number of strictly endemic species, Caño Negro stands out for acting as a “Noah’s ark” for plants that have disappeared from other parts of Central America due to agriculture and livestock farming.",
        flora_unique4_desc2: "It also preserves valuable populations of rare or historically pressured species, such as mahogany <em>(Swietenia macrophylla)</em>.",

        fauna_label: "Fauna",
        fauna_title: "A diversity shaped by water and the seasons",
        fauna_subtitle: "The fauna of Caño Negro responds directly to the wetland’s dynamics. At some times, water surfaces and aquatic birds dominate; at others, mudflats and open areas favor new species movements.",
        fauna_box1_title: "Birds",
        fauna_box1_desc: "Includes migratory and resident birds; it is the most abundant group and one of the refuge’s greatest attractions.",
        fauna_box2_title: "Mammals",
        fauna_box2_desc: "Notable are 90 species of bats and 70 terrestrial species, including felines, primates, and other species associated with forests and wetlands.",
        fauna_box3_title: "Fish",
        fauna_box3_desc: "Essential for the aquatic balance of the wetland. The gaspar stands out as a symbolic species of great biological value.",
        fauna_box4_title: "Reptiles",
        fauna_box4_desc: "Caimans, crocodiles, turtles, and other reptiles linked to lagoons, shores, channels, and flood-prone areas stand out.",
        fauna_box5_title: "Amphibians",
        fauna_box5_desc: "Ecological indicators of the ecosystem’s environmental status.",

        birds_tag: "Featured fauna",
        birds_title: "Birds",
        birds_desc1: "Caño Negro is a sanctuary for birdwatching. This group is the wetland’s greatest attraction due to the presence of resident and migratory species that use the wetland for feeding, resting, and reproduction.",
        birds_desc2: "<strong>Residents:</strong> Approximately 206 species inhabit the refuge year-round.<br><strong>Migratory:</strong> Around 101 species visit the wetland during the Northern Hemisphere winter.",
        birds_desc3: "<strong>Key species:</strong> include the Agami Heron (<em>Agamia agami</em>), the Jabiru (endangered), the Roseate Spoonbill, the Wood Stork, and the Snakebird or Anhinga (<em>Anhinga</em>).",
        birds_desc4: "This avian richness makes Caño Negro one of the most important birdwatching areas in Costa Rica.",
        birds_side_title: "Key facts",
        birds_side_1: "Approximately 315 to 400 species",
        birds_side_2: "Largest group in the wetland",
        birds_side_3: "Presence of resident and migratory species",
        birds_side_4: "Great value for observation and photography",

        mammals_tag: "Land fauna",
        mammals_title: "Mammals",
        mammals_desc1: "Caño Negro hosts a wide variety of mammals. Among them stand out species of bats, felines, monkeys, and other animals that find refuge in forests, flood-prone areas, and riverside zones of the wetland.",
        mammals_desc2: "This diversity reflects the ecological complexity of the refuge, since the presence of mammals depends on vegetation cover, water availability, and the connection between different natural environments.",
        mammals_desc3: "Among the most representative mammals recorded are the <strong>Jaguar</strong>, the <strong>Tapir</strong>, the <strong>Puma</strong>, and the <strong>Manatee</strong>, the latter being very rare and endangered. It is also common to observe primates such as the <strong>Howler Monkey</strong>, the <strong>White-faced Monkey</strong>, and the <strong>Spider Monkey</strong>.",
        mammals_side_title: "Representative species",
        mammals_side_1: "White-faced monkey",
        mammals_side_2: "Howler monkey",
        mammals_side_3: "Puma",
        mammals_side_4: "Tapir",

        fish_tag: "Aquatic life",
        fish_title: "Fish",
        fish_desc1: "The Frío River water system hosts species of great scientific and commercial value, with the <strong>Gaspar (Atractosteus tropicus)</strong> being one of the most representative. This fish is considered a “living fossil” due to its prehistoric appearance, and Caño Negro is one of the few places where it is protected.",
        fish_desc2: "In addition to the gaspar, other important species inhabit the area, such as the <strong>Tarpon</strong>, <strong>Guapote</strong>, <strong>Snook</strong>, and various <strong>Mojarras</strong>, all essential for the balance of the aquatic ecosystem.",
        fish_desc3: "Their presence maintains the food chain and is closely related to water dynamics, aquatic vegetation, and the reproduction of other species associated with lagoons, channels, and flooded areas.",
        fish_side_title: "Highlight",
        fish_side_1: "Approximately 49 to 55 species",
        fish_side_2: "Includes the Gaspar",
        fish_side_3: "Direct relationship with lagoons and channels",
        fish_side_4: "Key to aquatic ecological balance",

        reptiles_tag: "Riverside environments",
        reptiles_title: "Reptiles",
        reptiles_desc1: "The reptiles of Caño Negro are closely linked to channels, lagoons, riverbanks, and dense vegetation areas. Caimans, turtles, basilisks, and iguanas are part of the wetland’s visual and ecological identity.",
        reptiles_desc2: "Their abundance shows the refuge’s ability to sustain species adapted to aquatic and semi-aquatic ecosystems, where heat, water, and plant cover create ideal conditions for survival.",
        reptiles_desc3: "Caño Negro is famous for having one of the highest concentrations of <strong>Spectacled Caimans</strong> and <strong>Crocodiles</strong> in the northern region, as well as species such as the <strong>Jicotea Turtle</strong>, closely associated with the wetland’s bodies of water.",
        reptiles_side_title: "Common sightings",
        reptiles_side_1: "Spectacled caiman",
        reptiles_side_2: "Jicotea turtle",
        reptiles_side_3: "Basilisk",
        reptiles_side_4: "Green iguana",

        amphibians_tag: "Environmental indicators",
        amphibians_title: "Amphibians",
        amphibians_desc1: "Amphibians depend on humid and healthy environments, so their presence is an important sign of Caño Negro’s ecological condition. Frogs and toads actively participate in ecosystem balance and the natural control of insects.",
        amphibians_desc2: "Although they are less visible than other groups, their ecological value is enormous, since they react quickly to environmental changes and help us understand the health of the wetland.",
        amphibians_side_title: "Ecological importance",
        amphibians_side_1: "More than 30 species",
        amphibians_side_2: "Dependence on constant humidity",
        amphibians_side_3: "Natural insect control",
        amphibians_side_4: "Indicators of environmental condition",

        extra_label: "Biological diversity",
        extra_title: "Variety, seasonality, and wildlife",
        extra_subtitle: "The biodiversity of Caño Negro is also understood through seasonal changes, which modify fauna distribution and favor the observation of species uncommon in other parts of the country.",
        extra_card1_title: "Note on varieties",
        extra_card1_desc: "When speaking of “varieties” in biological terms, it refers to genetic diversity within species. In Caño Negro, this richness is driven by the wetland’s natural dynamics.",
        extra_card2_title: "Dry season",
        extra_card2_desc: "During the dry season, from January to April, water is reduced to small lagoons, concentrating fauna and facilitating the observation of specific aquatic bird species.",
        extra_card3_title: "Special sighting",
        extra_card3_desc: "This dynamic makes it possible to observe species and behaviors not always seen in other parts of Costa Rica, increasing the refuge’s ecological and tourism value.",
        extra_card4_title: "Fun fact",
        extra_card4_desc: "Caño Negro is considered one of the most important wetlands in the world due to the extraordinary density of wildlife it can support per hectare.",

        closing_tag: "CAÑO NEGRO",
        closing_title: "The richness of the wetland lies in the relationship between its flora, fauna, and water",
        closing_desc: "Understanding Caño Negro means understanding how every plant, every water surface, and every species are part of a living system. Its conservation protects one of Costa Rica’s most valuable ecological landscapes.",

        btn_more_info: "See more information",
        footer_text: "© 2026 ADI Caño Negro - All rights reserved"
    }
};